# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1799df254e653562136a2b6d062881556e74a3485cbf14691d6343fa8fa31b9fb99bbcf8751351ccfd544449854576c89755106ef810f3d358a29076555e957d

test:
  secret_key_base: 2667f2a119872aa0dbb0243e62ac7e2042ffc384b4bac90672a77b7ad4f2af978ca1c5ac6fb1db00dc9e7db2c295e815e2fa4b597774f18265013d187fc0b830

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
